name: app1
description: A sample Flutter application
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_codegen_monorepo_example_graphql:
    path: ../packages/graphql
  graphql_codegen_monorepo_example_feature1:
    path: ../packages/feature1
  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Add other dev dependencies here

flutter:
  # Add flutter specific configurations here

# Add any other necessary fields and values here
